nano.mk
=> Update nano to 4.9.3

CONTRIBUTING.md, README.md, build_info/com.openssh.sshd.plist, build_info/openssh.control, build_info/openssh.postinst, build_info/sshd-keygen-wrapper, grep.mk.template, openssh.mk
- Add sshd-keygen-wrapper
- Make daemon use sockets
- Port 2222 local ssh
- ~~Adjust postinst~~ Remove postinst
=> Change openssh to SSHListener format and add port 2222 for local ssh.

tmux.mk
=> Fixes tmux issue #19.

git.mk
Information on the changes: https://github.blog/2020-07-27-highlights-from-git-2-28/
=> Update git to 2.28.0

.gitmodules, build_info/pfetch.control, pfetch.mk
Current says the OS is macOS however, a [PR has been opened](https://github.com/dylanaraps/pfetch/pull/67) to fix that on upstream so it will say macOS until that is merged, or some other fix is made.
=> Add pfetch

nano.mk
=> Update nano to 5.0

build_info/futurerestore.control, futurerestore.mk
=> add futurerestore

futurerestore.mk
=> fix futurerestore setup

build_info/libprotobuf-dev.control, build_info/libprotobuf.control, build_info/mosh.control, build_patch/mosh/ios.diff, libprotobuf.mk, mosh.mk
Three PRs in 4 hours, this may be a new personal record.
=> Add mosh and libprotobuf

pacman.mk
Sorry, I forgot to fix that when I PR'd it.
=> Set pacman to SUBPROJECT instead of STRAPPROJECT

build_info/libsigc++-2.0-0v5.control, build_info/libsigc++-2.0-dev.control, libsigcplusplus.mk
This was way easier than boost.
=> Add libsigc++

gawk.mk
as instructed here --> https://twitter.com/Diatrus/status/1314045688804601856
=> fix gawk-locale Section

basic-cmds.mk
add `-1` to `DEB_BASIC-CMDS_V`
=> force basic-cmds into proper section

LINUX.md, README.md
Should get you from 0-100 on Linux real quick.
Includes step-by-step instructions for every part of setup.
=> Add more detailed Linux install instructions

Makefile, apt.mk, build_patch/apt/ios.diff
=> Add apt manpages

build_info/libass-dev.control, build_info/libass9.control, build_info/libharfbuzz-bin.control, build_info/libharfbuzz-dev.control, build_info/libharfbuzz-gobject0.control, build_info/libharfbuzz-icu0.control, build_info/libharfbuzz-subset0.control, build_info/libharfbuzz0b.control, build_info/librubberband-dev.control, build_info/librubberband2.control, build_info/libsamplerate0-dev.control, build_info/libsamplerate0.control, build_info/rubberband-cli.control, build_info/vi.postinst, build_patch/rubberband/ios.diff, harfbuzz.mk, libass.mk, libsamplerate.mk, rubberband.mk
Untested ~~(as with all my working ones :P)~~ (kinda tested)
=> Add harfbuzz and libass

build_info/cowsay-off.control, build_info/cowsay.control, cowsay.mk
=> Add cowsay

build_info/term-fireworks.control, build_patch/term-fireworks/properly-clear-screen.diff, term-fireworks.mk
Not sure how many firework displays there are going to be this year, let's get those numbers up.
=> Add term-fireworks

build_info/libyaml-0-2.control, build_info/libyaml-dev.control, libyaml.mk
[haha L](https://up.psty.io/343/Screen_Shot_2020-12-29_at_12.21.19_AM.png)
=> Add libyaml

build_info/dpkg-repack.control, dpkg-repack.mk
=> Add dpkg-repack

nano.mk
=> Update nano to 5.5

bender.mk
libhooker-configurator 1.1's release added a new configuration type, so I updated bender with it
=> update bender to 1.1

build_info/libebml-dev.control, build_info/libebml5.control, libebml.mk
Generated cmake files are included in the libebml-dev package as these are needed for libmatroska.
=> Add libebml

Makefile, libgpg-error.mk, openssl.mk
=> x86 strap building

dimentio.mk
=> update dimentio to latest commit and macOS

build_patch/neofetch/neofetch_iOS_fix.diff, neofetch.mk
Thanks you @NotZoeyDev for providing support for these devices and helping with the initial patch.
=> Added new devices information

axel.mk, build_info/axel.control
=> Add axel (Closes #542)

build_info/libz-ng-dev.control, build_info/libz-ng2.control, zlib-ng.mk
I need to know how to debianise this
=> add zlib-ng

dimentio.mk
This PR updates ``dimentio`` to the latest commit available, with new changes (that are never documented because who cares?)
=> Update dimentio to latest commit

build_info/rc.control, build_info/tcsh.control, build_patch/rc/0000-test.patch, build_patch/rc/10_which-error-handling.patch, build_patch/rc/20_panic-attribute-noreturn.patch, build_patch/rc/30_trip-hide-envvars.patch, build_patch/rc/40_manpage-typography.patch, build_patch/rc/50_reproducible-build.patch, build_patch/tcsh/0000-fix-tcsh-gethost.patch, rc.mk, tcsh.mk
I've also done ksh, but i've had to do some horrendous patching of the `meson.build`, so I'm not going to include that here. I have it on a seperate branch on my fork. rc is fully functional on my iOS 14 device. tcsh is unable to access the termcap database, so that needs to be fixed as well.
=> add tcsh and rc

build_info/help2man.control, help2man.mk
Programs that support this should probably be recompiled
=> add help2man

Makefile, build_info/audio.xml, build_info/libao-common.control, build_info/libao-dev.control, build_info/libao4.control, build_info/libjson-c-dev.control, build_info/libjson-c5.control, build_info/libsoundio-dev.control, build_info/libsoundio-progs.control, build_info/libsoundio2.control, build_patch/libao-ios/ios.patch, build_patch/libsoundio-ios/cmake.patch, build_patch/libsoundio-ios/ios.patch, libao.mk, libjson-c.mk, libsndfile.mk, libsoundio.mk, libsoxr.mk, libspeex.mk, rav1e.mk
Holding off PulseAudio and PortAudio for now
=> Sound Libraries

lzfse.mk
Fix GITHUB_ARCHIVE for lzfse, fixing downloading.
=> Fix lzfse GITHUB_ARCHIVE

build_info/hello.control, build_patch/hello/procursus.diff, hello.mk
I am surprised that this isn't in Procursus yet.
=> Add GNU hello

Makefile
=> Fix building in non-English environment.

build_info/chezmoi.control, chezmoi.mk
Add chezmoi from https://github.com/twpayne/chezmoi
Needs Go 1.16 (#579), and it compiles just fine on my iPhone and ARM Mac.
=> Add chezmoi

build_info/libsystem-man.control, libsystem-man.mk
This adds man2 (syscalls), man3 (libc functions), and man4 (device files) manpages
=> add libsystem-manpages

build_info/txt2man.control, txt2man.mk
This PR adds ``txt2man``, a CLI that converts flat ASCII text to man page format.
=> Add txt2man

build_info/lrzip-next.control, lrzip-next.mk
I'm unsure where to get the description from, so I haven't pushed the control file yet
=> add lrzip-next

build_info/tmux.control.macosx
=> Fix tmux packaging for macos

build_info/xtrace.control, xtrace.mk
I used salsa because I couldn't find any other reliable source to get the code from.
=> add xtrace

build_info/hexedit.control, hexedit.mk
This PR adds ``hexedit``, a Hexidecimal/ASCII editor.
=> Add hexedit

Makefile
=> add check for file

sdl2.mk
libvpx wouldn't compile because of this
=> Fix sdl2 configure flags

Makefile, makefiles/uikittools.mk
=> all da targets

Makefile
Speed up make with MAKEFLAGS(jobs, loadavg)
=> Speed up make with MAKEFLAGS(jobs, loadavg)

CONTRIBUTING.md
I can't believe I missed this. Oops.
=> Completely rewrite contributing guidelines

build_info/libdca-dev.control, build_info/libdca-utils.control, build_info/libdca0.control, makefiles/libdca.mk
don't mind me, just adding more videolan stuff
=> Add libdca

build_info/libsigsegv-dev.control, build_info/libsigsegv2.control, makefiles/libsigsegv.mk
Another generated PR (tested)
libsigsegv provides a way for applications to handle segfaults gracefully.
=> Add libsigsegv

makefiles/tsschecker.mk
Update tsschecker(iOS 15 beta support)
=> Update tsschecker(iOS 15 beta support)

Makefile, makefiles/jq.mk
- PACK: Follow symlinks when copying docs
- jq: Fix pack
=> Fix PACK and jq

Makefile
Come on people, don't put spaces in your PATH.
=> Makefile: Put PATH in quotes

build_info/xpwn.control
When i tried installing xpwn, it couldn't find libpng16 bc it wasnt a dependency.
=> Update dependency of xpwn

makefiles/dropbear.mk
=> dropbear: Fix build

makefiles/dpkg.mk, makefiles/gnupg.mk, makefiles/sudo.mk, makefiles/uuid.mk, makefiles/xz.mk
fix dpkg, sudo, uuid, xz and gnupg
=> fix a bunch of stuff compiling on linux

makefiles/openpam.mk
openPAM changed their website around.
=> Fix openpam download

makefiles/ncurses.mk
=> Fixed a small packaging mistake.

build_info/libfftw3-3.control, build_info/libfftw3-bin.control, build_info/libfftw3-dev.control, build_info/libfftw3-double3.control, build_info/libfftw3-long3.control, build_info/libfftw3-single3.control, build_info/powder.control, makefiles/fftw.mk, makefiles/powder.mk
This was tested on both `darwin-amd64` and `darwin-arm64`. I was not able to test on iOS because SDL apps do not work through X11 on iOS currently.
=> Add The Powder Toy and FFTW

makefiles/pcre.mk, makefiles/pcre2.mk
=> Fix pcre and pcre2 download links

makefiles/ipsw.mk
=> ipsw: Update to 3.1.11

build_misc/powder/Info.plist, makefiles/powder.mk
I could not get a Powder.app to work on iOS. I will continue trying but
it's not a priority.
=> powder: Add Powder.app

makefiles/tsschecker.mk
=> Update tsschecker to v367

build_info/libxss-dev.control, build_info/libxss1.control, makefiles/libxss.mk
=> add libxss

makefiles/tor.mk
=> Update tor to 0.4.6.8

build_info/notifyutil.control, build_misc/entitlements/notifyutil.xml, build_patch/notifyutil/fixes.diff, makefiles/notifyutil.mk
=> Add notifyutil(1)

Makefile, makefiles/diskdev-cmds.mk, makefiles/file-cmds.mk, makefiles/gettext.mk
=> Fix building and packaging of some STRAPPROJECTS

build_info/file.control, makefiles/file.mk
=> improve file depends

build_info/plistbuddy.control, build_info/unxip.control, makefiles/darling-utils.mk
=> Add unxip and PlistBuddy

build_info/libxss1.control
=> Fix libxss1 control again

build_patch/neofetch/new_idevices.diff, makefiles/neofetch.mk
=> Updated neofetch to latest commit, fixed packaging, and added a patch for new iDevices

build_info/doc-cmds.control, makefiles/doc-cmds.mk
=> doc_cmds-55

makefiles/python3.mk
=> fix python3 compile for Linux and FreeBSD

build_info/xonsh.control, makefiles/xonsh.mk
This PR includes the following changes
- Update xonsh to a commit hash
- Fix minor typo in package control file
- Fix a small issue with xonsh and its command, `xonsh webconfig`, not working (fixed in upstream)
=> xonsh: Update xonsh to a commit hash

build_info/rar.control, build_info/unrar.postinst, makefiles/rar.mk, makefiles/unrar.mk
This program is shareware and you must register it after 40 days of use.
=> add rar, update unrar

makefiles/hexedit.mk
- If it compiled on my 2015 iPod touch, it should compile on other systems.
=> hexedit: Update to v1.5

makefiles/defaults.mk
This PR updates ``defaults`` to 1.0.1
- If it compiled on my 2015 iPod touch, it should compile on other systems.
=> defaults: Update to 1.0.1

makefiles/meson.mk
This PR updates ``meson`` to 0.61.2
- If it compiled on my 2015 iPod touch, it should compile on other systems.
=> meson: Update to 0.61.2

makefiles/gh.mk
Built successfully for darwin-* on darwin-amd64, works on darwin-amd64.
=> gh: bump to 2.5.1

build_tools/new_package.sh
- Added dialog UI for `build_tools/new_package.sh`
- Added feature to list build systems in CLI mode:
- Use `command -v`
=> feat(new_package): terminal dialog, list build systems for cli mode

build_misc/templates/package.control, build_tools/new_package.sh
`./build_tools/new_package.sh` now generates a control file with it.
=> feat(new_package): generate a basic control file as a base

makefiles/darling-utils.mk
=> Small spelling error and white space removal.

makefiles/unzip.mk
=> Updated unzip to latest.

Makefile, build_patch/openssl/0001-armv7-fix-atomic.patch, makefiles/coreutils.mk, makefiles/diskdev-cmds.mk, makefiles/grep.mk, makefiles/openssl.mk
Honestly: No, but really i don't see why anyone would work **and debug** iOS 9 armv7 ramdisk builds. I'm just educated guessing this isn't duplicated.
No, this only contains build fixes
I built and tested iOS 9 armv7 ramdisk target and ran it on iPhone4s. It works as expected.
Each of the commits describe what they change and why.
=> Armv7 ios9 ramdisk

build_misc/entitlements/kextload.plist
This was too small for a PR, but I don't have r/w to main so, here it is.
=> kext-tools: Fix kextload entitlements

mirrors.txt
*  [x] This Pull Request doesn't contain any package additions; it's a small change (e.g README change)
My mirror is updated every 6 hours using the rsync script.
=> Add my Procursus mirror

build_patch/aria2/0001-remove-connection-limit.patch, makefiles/aria2.mk
This also adds a patch to remove the 16 connection limit
=> aria2: Update tp 1.36.0

build_info/bison.control
=> Add libtextstyle0v5 dependency to bison

makefiles/libgif.mk
=> libgif: Correctly download source tarball

makefiles/ipsw.mk
=> Update ipsw to 3.1.189

build_info/xcodegen.control, makefiles/xcodegen.mk
=> add xcodegen

makefiles/file.mk
This PR updates `file` to its latest release, that being 5.43.
=> file: Update to 5.43

build_info/swiftlint.control, makefiles/swiftlint.mk
iOS build currently isn't possible due to one of the project's dependencies using Process() which isn't available on iOS.
=> add swiftlint

makefiles/ipsw.mk
=> Update ipsw to 3.1.193

makefiles/git.mk
=> Updated git to 2.39.1

makefiles/ipsw.mk
=> Update ipsw to 3.1.255

build_patch/libplist/array_methods.patch, build_patch/libplist/cpp_methods.patch, makefiles/libplist.mk
=> Update libplist and add c++ patches

Makefile, makefiles/lsof.mk, makefiles/notifyutil.mk, makefiles/pam-modules.mk, makefiles/pongoterm.mk, makefiles/system-cmds.mk, makefiles/top.mk
Now uses https://github.com/apple-oss-distributions
=> Remove all references to opensource.apple.com

makefiles/unzip.mk
This PR updates unzip to 6.0-28.
=> unzip: Update to 6.0-28

build_info/just.control, makefiles/just.mk
=> Add just package

makefiles/libgmp10.mk
See https://github.com/actions/runner-images/issues/7901#issuecomment-1633428134 for more details.
=> GMP project has banned the GitHub Actions
