ProcursusTeam/Procursus

- Makefile
- Add Xcode default toolchain to $PATH when building on Darwin Hosts.
> Improve building on Darwin hosts.

- bash.mk
This will fix using bash with scripts on certain jailbreaks, namely u0. It also bumps the subversion number.
> Fix Bash Not Respecting Shebangs on Some Installs

- Makefile
On macOS it is using `/usr/bin/groff` instead of brew groff
> fix groff detection when using brew

- darwintools/Makefile
**Fixes this error:**
```
$ make clean
Makefile:66: Building for iOS
Makefile:122: Building on MacOS
rm -rf /Users/absidue/dev/github/Procursus/build_work/iphoneos-arm64/1600 /Users/absidue/dev/github/Procursus/build_base/iphoneos-arm64/1600 /Users/absidue/dev/github/Procursus/build_stage/iphoneos-arm64/1600
git submodule foreach --recursive git clean -xfd
Entering 'uikittools'
git submodule foreach --recursive git reset --hard
Entering 'uikittools'
HEAD is now at 373c012 No longer support calling uicache without -a
rm -f darwintools/.build_complete
make -C darwintools clean
rm sw_vers firmware
rm: sw_vers: No such file or directory
rm: firmware: No such file or directory
make[1]: *** [Makefile:21: clean] Error 1
make: [Makefile:583: clean] Error 2 (ignored)
```
> Fix clean target erroring when darwintools isn't built

- apt.mk
- dpkg.mk
Due to the way Debian manages their servers updating dpkg to 1.20.5, or changing the download url is necessary.
> Update apt and dpkg

- berkeleydb.mk
The version update has caused the old version to be removed from the mirror (or just moved) so updating the version is required to download the source code.
> Update berkleydb to 18.1.40

- build_info/mosh.control
Issue this fixes:
```
~/iOS-Projects/Procursus moshfix* 9s
❯ mosh tester
The locale requested by LANG=en_US.UTF-8 isn't available here.
Running `locale-gen en_US.UTF-8' may be necessary.
mosh-server needs a UTF-8 native locale to run.
Unfortunately, the local environment ([no charset variables]) specifies
the character set "US-ASCII",
The client-supplied environment (LANG=en_US.UTF-8) specifies
the character set "US-ASCII".
sh: locale: command not found
Connection to 192.168.1.87 closed.
/usr/bin/mosh: Did not find mosh server startup message. (Have you installed mosh on your server?)
```
> Mosh: add gettext-localizations and libssl1.1 dependencies

- Makefile
Prevents me from getting asked everyweek what package has `clear`, also fixes an oversight by me when updating this function based of [this comment in which you said `ncurses-bin` should go in the bootstrap](https://discord.com/channels/715793185019920405/760637144049123328/763268393431859201).
> Add ncurses-bin to bootstrap tarball

- build_info/dialog.control
- dialog.mk
To keep parity with debian, dialog is not being split, it also is only having a static lib. I can't install the headers without dialog-config so that has to get deleted.
> Add dialog

- frei0r.mk
- libvidstab.mk
- libvpx.mk
How do so many get pass review **except** vi
> Remove unnecessary STRAPPROJECTS

- build_info/libass-dev.control
- build_info/libharfbuzz-dev.control
- harfbuzz.mk
- libass.mk
instead of libfreetype6-dev.
Currently, it is impossible to install libharfbuzz-dev and libass-dev because they have a dependency on libfreetype6-dev, which does not exist. This package is in Procursus, but it is called libfreetype-dev.
I can bump the deb version if needed.
> Fix libharfbuzz-dev and libass-dev to refer to libfreetype-dev

- libjpeg-turbo.mk
Note: This package has a beta package in the works for version 2.1. If that get pushed to stable this package maybe updated once again.
> Update libjpeg-turbo to version 2.0.6

- bender.mk
This fixes an issue where it would just crash instead of showing a help screen if you did `bender list`
> Update bender to v1.1.1

- Makefile
`bash --version` gives on my machine
```
GNU bash, Version 5.1.4(1)-release (x86_64-apple-darwin20.2.0)
```
Thus you should do case insensitive grepping for the string.
> Case insensitive grepping

- build_info/gzip.control
Since the new updates to ``file-cmds``, users were affected by a small, but pretty significant "restriction", which removed Filza and other dependencies once upgrading. This PR fixes that by removing such "restriction" from ``gzip``'s control file, allowing affected users to install Filza again without issues.
> Critical fix for gzip

- Makefile
This small, but pretty significant PR filters iPods in the Makefile, preventing Procursus from using incorrect variables.
What happens is that, prior to this change, Procursus would "report" that packages were being built on macOS, despite that not being the case (they were actually being built on an iPod). This fixes the issue, meaning that iPods are now recognized as an iOS platform, and the correct iOS variables are used.
> Critical: Filter out iPods in Makefile

- zsh.mk
This PR provides a small change to ``zsh`` and its flags to moves zsh-related files back to their designated path, ``/usr/share/zsh/``, maintaining consistency. This also bumps the version as means of pushing a new update to the package. Suggestions to changes are welcome!
> Revert back file structure consistency on zsh

- youtube-dl.mk
This PR updates ``youtube-dl`` to the latest released version. This should fix any errors users experience with older installations. Go outside with your friends and prank your boss today!
> Update youtube-dl to latest version

- build_info/siguza-utils.control
- siguza-utils.mk
This PR adds ``siguza-utils``, which includes ``bindump``, ``clz``, ``dsc_syms``, ``rand``, ``strerror``, ``vmacho``, and ``xref`` from [Siguza/misc](https://github.com/Siguza/misc), in one package. The only exception is ``mesu``, which seems to no longer work.
This is my first, somewhat usable package (that isn't just a control file), so I do suggest giving me criticism on how I've compiled this. I've attempted to use functions which make things like downloading and extracting a package easier, but I'm sure this can be improved. Software provided as-is, blah blah not much from here will do anything bad.
> Add siguza-utils

- speedtest-cli.mk
This PR updates ``speedtest-cli`` to the latest version, 2.1.3, which addresses the following issues
- Address issue where ``ignore_ids`` may be empty or have empty values
- Address issue where a test server may return an HTTP error during upload or download
There's not much to this PR; I tested building on iOS and everything seems to be working. Remember to stay hydrated :)
> Update speedtest-cli to latest version

- build_patch/make/0000-fix-make-eperm.patch
- make.mk
I guess make sometimes executes commands directly instead of in a sub shell, so it needs an EPERM patch as well
> GNU Make EPERM patch

- build_info/ldid.control
This PR fixes ``ldid``'s libplist dependency, which was incorrectly specified. Make sure you don't have typos in your essay!
> Chore: Fix ldid dependency

- build_info/xserver-xephyr.control
Turns out Xephyr needs libgl-mesa-glx (it queues dri anyways) or else the command won't even run.
> Fix Xephyr depend

- axel.mk
- bash-completion.mk
- bsd-progress.mk
- chezmoi.mk
- cowsay.mk
- hello.mk
- libao.mk
- libimobiledevice.mk
- libpam-google-authenticator.mk
- libsoundio.mk
- msgpack.mk
- mtree-netbsd.mk
- nekofetch.mk
- opendoas.mk
- openpam.mk
- progress.mk
- rc.mk
- redis.mk
- snaprestore.mk
- ye.mk
- zpaq.mk
This PR transitions all packages coming from Github to the ``GITHUB_ARCHIVE`` function (introduced by absidue in [#419](https://github.com/ProcursusTeam/Procursus/pull/419)). The only exceptions are packages that don't come from Github, or get their tarballs from the projects' Github Release tab. 
From this PR on, new additions should, and (likely) will be required to use the function if the package comes from Github.
> Globalize GITHUB_ARCHIVE

- youtube-dl.mk
This PR updates ``youtube-dl`` to the latest released version, 2021.04.17, and retrieves the tarballs' signature, which is later checked with the ``PGP_VERIFY`` function. Making this into a draft until I've confirmed everything works.
> Minor changes to youtube-dl

- libsystem-man.mk
This fixes the double zst issue. I also updated the tarball on my site to remove redundant entries we might already have (pam, libpcap (in the future), etc).
> Fix manpages

- build_info/libuv1.control
- build_info/libuv1.control.macosx
- libuv1.mk
This fixes EPERM issues on anything that uses libuv for spawning files (which includes NodeJS). Closes #689
> libuv1 liobiosexec

- Makefile
This PR adds back the ``extreme-clean`` option, which removes all files (including compiled debs) from the working tree.
> Repopulate extreme-clean

- build_patch/glib2.0/removecocoa.diff
This is so that gir bindings can be built for gnome stuff since both dylibs(host and target) must contain the same symbols.
> Patch to remove cocoa stuff for glib2.0

- Makefile
This small PR adds iOS as a valid platform in a Makefile error that lists which platforms are supported as build systems. 0 functionality changes were made.
> Chore: Include iOS in Makefile error

- build_info/system-cmds.control
- system-cmds.mk
This critical PR fixes a root problem, specifically targeting Chimera users, who's entire bootstrap would break when upgrading ``system-cmds``. This was caused due to the order in which upgrades were installed; ``libiosexec1`` should now be installed beforehand, and upgrades for Chimera users should now work.
Note that this issue only occurs on devices that have recently installed Chimera; users with an already bootstrap'd device should not be affected by this issue. In case this issue pops its head up again, Chimera users will be required to install ``libiosexec1`` first before upgrading other packages, or everything will be borked.
> Critical: Fix system-cmds and Chimera

- build_patch/upx/fix-big-sur-compression.patch
- upx.mk
Currently `upx` does not work with macOS Big Sur and later. This has been fixed upstream, however it hasn't made its way into a release yet.
> Backport upx fix for big sur

- Makefile
- this adds support for compiling for 1800
- darwin-amd64 compiles and the binaries runs
- thread_state.h should not be downloaded on 1800
> macOS 12 (1800) support

- build_info/python3-prompt-toolkit.control
- python3-prompt-toolkit.mk
This PR adds ``python3-prompt-toolkit``, a library that makes it easier to make command-line applications in Python; this is a dependency needed by ``xonsh``, and is also an alternative to GNU ``readline``.
> Add python3-prompt-toolkit

- build_info/python3-prompt-toolkit.control
- makefiles/python3-prompt-toolkit.mk
- makefiles/xonsh.mk
This PR is a small update to ``xonsh`` to include a new dependency, [``python3-wcwidth``](https://github.com/jquast/wcwidth), which is provided by [#839](https://github.com/ProcursusTeam/Procursus/pull/839). Other changes made are listed in the commit message.
> xonsh: Add extra dependencies

- build_info/python3-wcwidth.control
- makefiles/python3-wcwidth.mk
This PR adds [``python3-wcwidth``](https://github.com/jquast/wcwidth), a Python library that allows applications to determine the size of a terminal window; this package is specifically useful for ``xonsh``.
> Add python3-wcwidth

- Makefile
This PR changes ``extreme-clean`` so that old downloaded project tarballs are cleared out when using the Makefile function. You can use this in case ``rebuild-(tool)`` fails with outdated tarballs you have on your build system setup.
> Makefile: Clear tarballs with extreme-clean

- build_info/logcleaner.control
- build_info/logcleaner.extrainst_
- build_info/logcleaner.prerm
- build_misc/moe.absolucy.logcleaner.plist
- makefiles/logcleaner.mk
simple launchctl script that runs `find /var/mobile/Library/Logs/CrashReporter -mindepth 1 -mtime +3 -delete` every 6 hours / on boot, which deletes crash logs older than 3 days.
originally i had some dumb program that did it, but turns out it can be done with just `find` (thanks @elihwyma)
> Adds logcleaner

- makefiles/youtube-dl.mk
This PR updates ``youtube-dl`` to v2021.06.06. Specific changes are listed in the commit message.
> Update youtube-dl to 2021.06.06

- build_info/python3-glances.control
- makefiles/python3-glances.mk
This PR adds ``python3-glances``, a cursed-based monitoring tool based on ``python3-psutil``. This package was requested on [#857](https://github.com/ProcursusTeam/Procursus/issues/857).
> Add python3-glances

- .github/workflows/assign-project.yml
This PR adds a workflow that automatically assigns PRs to the project board of ProcursusTeam. I'm unsure as to how I'm supposed to test this, but it's likely that will work once this is merged and someone opens either an issue or PR (since it also works with issues). 
Not much handling to be done, since the project board that these things are being assigned are already automated; this just removes the hassle of one of the team members adding new PRs and issues to their corresponding places.
> Auto assign PRs to project board

- .github/workflows/assign-project.yml
This PR fixes the small workflow introduced in [#893](https://github.com/ProcursusTeam/Procursus/pull/893); the workflow no longer handles issues, since those can be added to the project board manually, and isn't a hassle. On top of that, not all issues filed apply to the project board.
> Fix #893: Correctly assign new PRs to PB

- README.md
This PR supersedes and closes [#895](https://github.com/ProcursusTeam/Procursus/pull/895), adding a Discord server reference to the README, making it easier to find on the project's "homepage".
> Supersedes #895: Add Discord server reference

- build_misc/templates/keyring.control
- build_tools/new_keyring.sh
This PR updates the keyrings generator to add the owner of the specific PGP key to the control file. When merged, newer keyrings will have the author field (but you can always opt out of this).
> Add author field to keyrings

- makefiles/darwintools.mk
Updates to firmware:
- Query MobileGestalt directly instead of parsing gssc
- Minor performance improvements
- Ensure all paths use `PREFIX` (please check the [firmware](https://github.com/zbrateam/Firmware) source code merging this pr)
> Update darwintools with newest firmware commit and bump version

- Makefile
- makefiles/ncurses.mk
Quiet some errors while we're here.
> Makefile: Add MEMO_NO_IOSEXEC to disable libiosexec linking

- Makefile
- makefiles/openjdk.mk
- Not every CPU is using SMT.
- Make this configurable instead of forcing to use all cores/threads.
- Rename variable as it's not a function
Probably a better name than `CORE_COUNT` can be used though.
> Rename GET_LOGICAL_CORES and make it configurable

- Makefile
runtime includes library validation, which requires any libraries to be
system or signed with the same Team ID in order to be loaded, this means
that anything signed with a valid cert that is not part of Hayden Seay's
team will not work.
\> ldid
dyld: Library not loaded: @rpath/libcrypto.3.dylib
Referenced from: /opt/procursus/bin/ldid
Reason: no suitable image found.  Did find:
/opt/procursus/lib/libcrypto.3.dylib: code signature in (/opt/procursus/lib/libcrypto.3.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
/opt/procursus/lib/libcrypto.3.dylib: stat() failed with errno=1
[1]    12218 abort      ldid
> Makefile: codesign with -o kill,hard,expires instead of -o runtime

- build_patch/python3/library-fallback.patch
- makefiles/python3.mk
This PR updates to python 3.9.9, and also adds alternate Procursus library paths (e.g. /opt/procursus/lib) to the Python lib search paths.
> Update python3 to 3.9.9

- build_info/siguza-utils.control
- makefiles/siguza-utils.mk
This PR updates `siguza-utils` to the latest commit. which makes it easier to build with a Makefile. Specific changes have been mentioned under the commit message.
> Update siguza-utils to latest commit

- build_tools/find_deps.sh
Hotfix for ``find_deps.sh``, making it use the ``OTOOL`` variable that the script checks for. Otherwise, why the hell check for it?
> chore: Actually use OTOOL variable

- makefiles/chezmoi.mk
----
- Bump chezmoi to 2.12.1
- Fixes filename in EXTRACT_TAR
- Provides version number, commit hash and build time in the binary as per chezmoi's [packaging guide.](https://www.chezmoi.io/developer/packaging/)
> chezmoi: slightly fix makefile and bump to 2.12.1

- Makefile
- build_info/base.conffiles
- build_info/doas.conffiles
- build_misc/pam/doas
build_info/*.conffiles should be reserved for files not in /etc that
need to be tracked in the conffiles.
We need to confirm Sileo, Zebra and Cydia will not choke on conffiles. Sileo and Zebra should work but the bundled versions in most jailbreaks is likely too old. Cydia will almost definitely need an update.
> Auto-generated DEBIAN/conffiles for all files in /etc

- makefiles/zlib-ng.mk
As this is a drop in replacement for zlib, perhaps we should be replacing all non-system binaries with this zlib-ng
> Update zlib-ng and make some modifications

- build_info/duf.control
- makefiles/curlie.mk
- makefiles/duf.mk
- makefiles/fzf.mk
- makefiles/mtr.mk
- Bumps mtr, fzf, duf, curlie to upstream versions
- Add duf's author
- Add shell completions for fzf, as well as shell keybindings (in `@MEMO_PREFIX@@MEMO_SUB_PREFIX@/share/doc/fzf`
- Build environment: darwin-amd64, macOS 12.2.1
- Tested building on: darwin-amd64, darwin-arm64, iphoneos-arm64
- Tested working on: darwin-amd64
> chore: bump various packages

- build_info/ktool.control
- build_patch/ktool/legacy_setup.patch
- makefiles/ktool.mk
- makefiles/pygments.mk
- makefiles/python3-kimg4.mk
- makefiles/python3-pyaes.mk
This PR updates ``ktool`` to its latest release (v1.0.0); some patches were required to add in order for the package to build on all architectures. All other changes have been documented under the commit message.
> ktool: Update to 1.0.0

- Makefile
-not_for_dyld_shared_cache is a ld option to mark a dynamic library that will
not got into dyld shared cache. No Procursus dylibs should go into dyld shared
cache, so we set it here. Setting this flag allows -undefined dynamic_lookup to
be used for dylibs that have an install name prefixed with /usr/lib. With this
flag, the linker will also skip adding additional information to the dylibs
generated, so we can save a little bit of disk space here. This flag is allowed
even with main executables even though it does not do anything.
Since LDFLAGS is actually passed to CC, we do -Wl,-not_for_dyld_shared_cache
here.
> Makefile: add -Wl,-not_for_dyld_shared_cache to LDFLAGS

- build_patch/apt/path.diff
- makefiles/apt.mk
builds fine for iphoneos-arm64/1{5..7}00 and darwin-a{md,rm}64/1700.
Appears to install and work fine for iphoneos-arm64/1700 and darwin-amd64/1700 (actually 1800 with 1700 bootstrap)
iphoneos-arm64 note: you may encounter issues with libiosexec-dev dependencies. If you do, please build and install libiosexec debs from the GitHub repo.
> apt: update to 2.5

- Makefile
Fix ramdisk target build after recent refractor and add TVOS ramdisk target
> fix ramdisk after recent refractor and add TVOS ramdisk target

- Makefile
- build_info/bash.control
- build_info/coreutils.control
- build_info/darwintools.control
- build_info/dash.control
- build_info/dpkg.control
- build_info/fish.control
- build_info/git.control
- build_info/golang-1.18-go.control
- build_info/libapt-pkg6.0.control
- build_info/libpython3.9.control
- build_info/make.control
- build_info/misc-cmds.control
- build_info/perl.control
- build_info/rc.control
- build_info/sudo.control
- build_info/system-cmds.control
- build_info/system-cmds.control.rootless
- build_info/tcsh.control
- build_info/toybox.control
- build_info/zsh.control
- makefiles/libiosexec.mk
Fixes #1274
This PR makes it so that when all of the following conditions are met, a `libiosexec1` depend is auto-inserted into the control file.
- `darwin` is not in `$(MEMO_TARGET)`
- The package name is not `libiosexec1` or `libiosexec-dev`
- The package contains at least one Mach-O binary
> Automatically insert libiosexec1 depend in PACK

- makefiles/dpkg-repack.mk
This PR updates `dpkg-repack` to the latest version, as 1.48 no longer exists (for whatever reason)
> dpkg-repack: Update to 1.50

- makefiles/xmlto.mk
This small PR adds `gnu-getopt` to the list of build dependencies of `xmlto`, while correctly downloading the source tarball, which was a breaking change introduced by Hayden after migrating to `DOWNLOAD_FILES`. 
Special thanks to [Nebula](https://github.com/itsnebulalol) for pointing out that `xmlto`'s Makefile was broken, as it would not download the source tarball correctly.
> xmlto: Specify gnu-getopt as a build dependency

- build_info/org.libimobiledevice.usbmuxd.plist
- makefiles/usbmuxd.mk
This small PR fixes a small mistake in the `usbmuxd`'s LaunchDaemon, which had a direct prefixed path, rather than it being dynamically changed based on the chosen target when building; this change fixes `usbmuxd` for `iphoneos-arm64-rootless`.
> usbmuxd: Dynamically add target prefix to daemon

- makefiles/bash.mk
This PR disables `bash`'s builtin `getcwd()`, which is broken (even NixOS says so, 4 years ago). This fixes the linked issue, involving a "Bad file descriptor", which is linked in the commit message.
Special thanks to opa334 for figuring out the cause and to Cameron Katri for guidance. You can find more info about the issue by just googling the flag.
> bash: Disable Bash's broken builtin getcwd()

- makefiles/nano.mk
This PR updates `nano` to its latest release, that being 6.4. No issues while compiling on macOS, for iOS 14.
> nano: Update to 6.4

- makefiles/hexedit.mk
This PR updates `hexedit` to its latest version, 1.6.
> hexedit: Update to 1.6

- build_tools/new_package.sh
This PR migrates `new_package.sh` to `DOWNLOAD_FILE(S)`, which was recently (as in probably months now) introduced by Hayden. This forces newly generated Makefiles to use these functions. Documentation on both of these functions can be found in the links below.
- [DOWNLOAD_FILE](https://github.com/ProcursusTeam/Procursus/wiki/Makefile-functions#download_file)
- [DOWNLOAD_FILES](https://github.com/ProcursusTeam/Procursus/wiki/Makefile-functions#download_files)
> new_package.sh: Migrate to DOWNLOAD_FILE(S)

- makefiles/meson.mk
This small PR updates `meson` to its latest version, 0.64.0.
> meson: Update to 0.64.0

- makefiles/xkeyboard-config.mk
This small PR adds missing build dependencies for `xkeyboard-config`. The package should build now without any missing dependencies.
> xkeyboard-config: Add missing build dependencies

- makefiles/diskdev-cmds.mk
On these versions, this file exists in stock. The package version is not bumped since there is no offical repositories that supports 1800+
> diskdev-cmds: Do not build dirs_cleaner on CFVER 1800+

- makefiles/xz.mk
This PR updates `xz` to the latest version, 5.2.8.
> xz-utils: Update to 5.2.8

- makefiles/bender.mk
In its current state, upstream cannot build `bender`; this change fixes that. On top of that, I've decided to patch in the author's new credentials, since they're no longer accepting pull requests.
Tested on iOS 12 & iOS 14, building directly on macOS.
> bender: Fix building on supported targets

- makefiles/lsd.mk
This PR updates `lsd` to its latest released version, 0.23.1. With this, the project should be able to compile, as the Makefile referred to a deleted repository, which I've taken the time to fix as well. Tested on iOS 12 and macOS 12.6.1.
> lsd: Update to 0.23.1

- Makefile
Currently, directories such as `build_base` are cleared out when running `make clean`, which is not the intention of that Makefile rule. Instead, `clean` and `extreme-clean` have been restructured so that their names are not misleading.
This PR does not include any packages, so no checklist, Katri.
> hotfix: Fix priorities in (extreme-)clean

- build_patch/tmux/fixcross.diff
- makefiles/tmux.mk
This PR updates tmux to its latest released version, 3.3a. Switching over to using GITHUB_ARCHIVE, as there are no noticable differences between tarballs from those in tmux's Releases and Github.
Tested on iOS 12, iOS 14, and macOS 12.6.1, building on macOS Monterrey.
> tmux: Update to 3.3a

- makefiles/dpkg-repack.mk
This PR contains the following changes, on top of `dpkg-repack` being updated to its latest released verison, 1.52
- Fix manpage's name header when generating. It's DPKG-REPACK(1), not STDIN(1)
- Improve sed pattern to set version variable. Not sure why Debian maintainers don't do it like this...
Tested on iOS 12, iOS 14, & macOS 12.6.1, building on iOS 12 and macOS 12.6.1.
> dpkg-repack: Update to 1.52

- makefiles/pam-modules.mk
There was an unnecessary -, and Apple also renamed the folder when extracting
> Fix pam-modules downloading

- makefiles/p7zip.mk
This little PR change URL for p7zip. It seems that there is an [organization](https://github.com/p7zip-project) that mantains this project. So the [previous repo](https://github.com/jinfeihan57/p7zip) now is a fork without releases.
Tested on iOS 15.7.1 building on macOS Monterrey (GitHub Actions).
> p7zip: Moved in new organization

- build_misc/templates/go.mk
This PR introduces the `-trimpath` flag to the Go Makefile template, while cleaning up things that are no longer necessary. For more information as to why this flag was introduced, check out Debian's hosted manpage of [`go-build(1)`](https://manpages.debian.org/unstable/golang-go/go-build.1.en.html#trimpath).
> templates: Add -trimpath to Go template

- mirrors.txt
quiprr no longer maintains their mirror, so it should be removed from the list hosted by Github.
> chore: Remove unmaintained mirror from list

- makefiles/libgpg-error.mk
It seems that `libgcrypt` [requires as optional `gpg-error-config`](https://github.com/ProcursusTeam/Procursus/blob/e2b8309e68ea60342e8ebef733837b7dfb6044d3/makefiles/libgcrypt.mk#L29) that is part of `libgpg-error`. Anyway with [update to 1.46](https://github.com/ProcursusTeam/Procursus/commit/892f546509beecb62f72d749b3bf07d943243feb) `libgpg-error` [deprecates `gpg-error-config`](https://dev.gnupg.org/T5923).
So this PR lets building properly `libgcrypt` and so all packages that depends on it like `apt`, cURL, `git`...
Tested on iOS 15.7.1 building on macOS Monterrey (GitHub Actions).
> libgpg-error: Enable install `gpg-error-config`

- makefiles/libxcrypt.mk
This PR updates libxcrypt to its latest released version, 4.4.33. While updating the package, changes under-the-hood we made to the Makefile. Tested on iOS 12, 14, & macOS 12.6.1, building on macOS.
> libxcrypt: Update to 4.4.33

- makefiles/ncurses.mk
This PR updates `ncurses` to its latest upstream version, 6.4. The update addresses several issues, [including one affecting vim instances within tmux.](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027435)
> ncurses: Update to 6.4

- makefiles/gzip.mk
This PR updates gzip to its latest released version, 1.12. Tested on iOS 12 and macOS 12.6.1, building on macOS.
> gzip: Update to 1.12

- makefiles/debianutils.mk
This PR fixes updating dash on rootless by copying the add-shell fix.
> Add fix for remove-shell on rootless

- makefiles/less.mk
This PR updates less to its latest released version, 608. The Makefile now checks the downloaded tarball with a PGP signature using `PGP_VERIFY`. Tested on iOS 12, 14, and macOS 12.6.1.
> less: Update to 608

- makefiles/grep.mk
This PR updates grep to its latest released version, 3.10. Notable changes to the Makefile are documented under the commit message. Tested on iOS 12, iOS 14, and macOS 12.6.1, building on macOS.
> grep: Update to 3.10

- makefiles/make.mk
This PR updates `make` to its latest version, 4.4.1. Tested on iOS 14 and macOS 12.6.1. Notes regarding changes are under the commit message.
> make: Update to 4.4.1

- makefiles/ninja.mk
This pull request updates ninja to its latest released version, 1.11.1. Rather than the Makefile handling a build directory, this change uses cmake's `-B` flag, introduced in 3.13+. Tested on iOS 12, 14, and macOS 12.6.1.
> ninja: Update to 1.11.1

- makefiles/htop.mk
This PR updates htop to its latest released version, 3.2.2. Some notable changes to the Makefile include
- Use pre-built release tarballs from Github over downloading the source from those generated **by** Github (with `GITHUB_ARCHIVE`)
- Verify release tarball checksum with `CHECKSUM_VERIFY`
Tested on iOS 12, iOS 14, and macOS 12.6.1, building on macOS.
> htop: Update to 3.2.2

- makefiles/jbat.mk
This PR switches Levin's jbat tool to using hack-different's re-host on Github, which already includes patches previously made (with further improvements). Tested on iOS 12, 14, and macOS 12.6.1, building on iOS 12.
> jbat: Use hack-different's Github instance

- makefiles/locsim.mk
This PR fixes building `locsim` on rootless targets. Bumping up the version should require users to update the package. Changes were documented under the commit message.
> locsim: Fix building for rootless targets

- Makefile
Several packages, e.g `libpng16` have several `*.la` files, some which are symbolic links. When packing, their parent files are deleted. In reality, parent files should be deleted alongside symbolic links pointing to them.
> Makefile: Delete .la symlinks when packing

- Makefile
When packages (particularly, libraries) are built, they're copied to `BUILD_BASE` so that they can be accessed by other packages when building. Seeing as libtool files are not necessary, `AFTER_BUILD` suffers from the issue addressed in #1404, which has been fixed here.
> Makefile: Delete .la symlinks after building

- Makefile
- build_misc/expat.pc
makes #1005 buildable for CFVER 1700+
> Makefile: Install expat.pc during setup on CFVER 1700+

- makefiles/xtrans.mk
This PR updates `xtrans` to its latest version. I noticed the package being broken as I looked around my installation, and decided to go ahead and fix that as well.
> xtrans: Update to 1.5.0

- mirrors.txt
This mirror has been wrongfully terminated from Oracle Cloud with no way to appeal it.
> chore(mirrors): remove Nebula mirror

- makefiles/xtrans.mk
Downgrade `xtrans` back to 1.4.0, as 1.5.0 breaks `libx11` with many macro errors in headers
> xtrans: Downgrade to 1.4.0

- makefiles/2048.mk
This PR updates `2048` to its latest released version, 1.0.1, fixing small errors during compiling (who copies a file that doesn't exist after they think they downloaded it?)
> 2048: Update to 1.0.1
